POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "pacozg",
    "firstName": "Francsico",
    "lastName": "Zavala",
    "password": "fullstack_2021",
    "email": "pako.zavala@gmail.com",
    "dateOfBirth": "1976-10-17",
    "height": 170,
    "weight": 74,
    "gender": "male",
    "country": "Finland",
    "goals": "Basketball, fitness, karate",
    "background": "I want to be tech PRO",
    "avatarPic": ""
}