POST http://localhost:3001/api/users
Content-Type: application/json

{
    "createdAt": "",
    "userType": "client",
    "username": "barbarella",
    "firstName": "Jane",
    "lastName": "Pokkinen",
    "password": "123chamaco",
    "email": "jane.pokkinen@gmail.com",
    "age": 38,
    "height": 160,
    "weight": 61,
    "country": "Finland",
    "hobbies": [
      "cooking", "movies", "wine"
    ],
    "motivation": "Wanna feel stronger"
}